all: bidding_system host player
bidding_system: bidding_system.c 
	gcc bidding_system.c -o bidding_system
host: host.c
	gcc host.c -o host
player: player.c
	gcc player.c -o player
clean:
	rm -f bidding_system host player
